version: '2'
services:
    dancekvartal-app:
        image: dancekvartal
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://dancekvartal-postgresql:5432/dancekvartal
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    dancekvartal-postgresql:
        extends:
            file: postgresql.yml
            service: dancekvartal-postgresql
